<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10333" started-at="2024-09-10T14:50:16Z" finished-at="2024-09-10T14:50:27Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10333" started-at="2024-09-10T14:50:16Z" finished-at="2024-09-10T14:50:27Z">
      <class name="com.vivek.testcase.LoginTest">
        <test-method status="PASS" signature="browserOpen()[pri:0, instance:com.vivek.testcase.LoginTest@464bee09]" name="browserOpen" is-config="true" duration-ms="8197" started-at="2024-09-10T20:20:16Z" finished-at="2024-09-10T20:20:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserOpen -->
        <test-method status="FAIL" signature="TC001_LoginTest()[pri:1, instance:com.vivek.testcase.LoginTest@464bee09]" name="TC001_LoginTest" duration-ms="901" started-at="2024-09-10T20:20:25Z" finished-at="2024-09-10T20:20:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Product] but found [Products]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Product] but found [Products]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.vivek.testcase.LoginTest.TC001_LoginTest(LoginTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC001_LoginTest -->
        <test-method status="PASS" signature="browserClose()[pri:0, instance:com.vivek.testcase.LoginTest@464bee09]" name="browserClose" is-config="true" duration-ms="1212" started-at="2024-09-10T20:20:26Z" finished-at="2024-09-10T20:20:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserClose -->
      </class> <!-- com.vivek.testcase.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
